spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id-ticket: ticket
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    topic:
      ticket-name: ticket_topics
